Add an undoing & redoing system to the editor
TerryCavanagh/VVVVVV pull request #1085
Opened 2023-12-21 00:32 UTC by AllyTally

## Changes:

It's very easy to make mistakes in VVVVVV's built-in level editor, with no way to undo them. This PR adds an undo and redo system, bound to CTRL+Z for undo and CTRL+Y for redo. The undo and redo stacks don't have any limits, but could easily happen in the future. VVVVVV's data is small enough where this should never be an issue, however.

No notes show up for undoing and redoing, because keeping track of what specific action you're doing may bloat the system, and would get annoying for the end-user. Notes are a bit annoying in general, even, but that's not relevant for this PR.

## Legal Stuff:

By submitting this pull request, I confirm that...

- [x] My changes may be used in a future commercial release of VVVVVV
- [x] I will be credited in a `CONTRIBUTORS` file and the "GitHub Friends"
  section of the credits for all of said releases, but will NOT be compensated
  for these changes

2024-10-01 06:56 UTC, InfoTeddy commented
Conflicts need to be resolved.

2024-10-01 18:22 UTC, InfoTeddy requested changes
Style pass.

2024-10-01 18:22 UTC, InfoTeddy commented on desktop_version/src/Editor.cpp
> +        ed.show_note(loc::gettext(undo ? "ERROR: Nothing to undo" : "ERROR: Nothing to redo"));
In general we try to keep all `loc::gettext` strings easily greppable. Please move the `loc::gettext` calls into the ternary, not surrounding it.

Speaking of which, you need to add these strings to the language files too.

2024-10-04 01:35 UTC, InfoTeddy requested changes

2024-10-04 01:35 UTC, InfoTeddy commented on desktop_version/src/Editor.cpp
> +    undo_buffer.clear();
When a new level is loaded, the undo buffer is cleared but not the redo buffer. So if there's anything in the redo buffer, you can press Ctrl+Y and that will be applied in the new level when it shouldn't be.

2026-04-11 22:30 UTC, NyakoFox commented
Rebased and force-pushed, no longer conflicts (and fixes an issue)

2026-04-22 00:25 UTC, flibitijibibo approved these changes
At a high level this looks good - if anybody's tested this would be good to get a +1 from them as well before merging.

2026-04-22 00:25 UTC, flibitijibibo commented on desktop_version/src/Editor.cpp
> +                        // Uncommit the past two actions
This could be improved with a 'why', in case someone looks at this and thinks it's just temporary kludge or something

2026-04-22 01:10 UTC, NyakoFox commented on desktop_version/src/Editor.cpp
> +                        // Uncommit the past two actions
Added a few comments to explain the logic, hopefully they makes sense!

2026-04-22 01:41 UTC, flibitijibibo approved these changes

2026-04-22 01:42 UTC, NyakoFox commented
I asked a few people to test; seems like we're getting some weird memory corruption to do with cross-room undos, so I'm looking into that right now.

2026-04-22 02:49 UTC, NyakoFox commented
Fixed the issue; it was just a missed conditional somewhere which caused the stack to inflate & save tile states which didn't change and relied on old data (which made things work strangely) -- not the "memory corruption" I assumed it was. I'm waiting on people to test now and I'll report back once no issues have been found!

2026-04-24 19:48 UTC, Daaaav requested changes
Few really small things, otherwise looks good I think!

2026-04-24 19:48 UTC, Daaaav commented on desktop_version/src/Editor.cpp
>          get_input_line(TEXT_SCRIPT, "Enter script name:", &entity->scriptname);
These two `get_input_line`s are inconsistent with each other - the new one adds a `loc::gettext` that the others didn't have (`get_input_line` is a rare case where the `loc::gettext` is done somewhere later)

2026-04-24 19:48 UTC, Daaaav commented on desktop_version/src/Editor.cpp
> +void process_editor_buffer(const bool undo)
`process_editor_buffer` is not a very clear name for a function that (I think) handles specifically the action of undoing or redoing.

2026-04-24 20:10 UTC, NyakoFox commented on desktop_version/src/Editor.cpp
> +void process_editor_buffer(const bool undo)
Changed to `handle_undo`.

2026-04-24 20:10 UTC, NyakoFox commented on desktop_version/src/Editor.cpp
>          get_input_line(TEXT_SCRIPT, "Enter script name:", &entity->scriptname);
Solved.

2026-04-24 20:11 UTC, NyakoFox commented
Fixed those; and I've gotten a few people to test again and they also say it looks good.

2026-04-24 20:12 UTC, Daaaav approved these changes

2026-04-25 17:45 UTC, flibitijibibo approved these changes

2026-04-25 17:46 UTC, merged