Fix segfault from attemptting to unwordwrap an empty string
TerryCavanagh/VVVVVV pull request #1125
Opened 2024-01-19 05:00 UTC by InfoTeddy

This fixes a segmentation fault caused by an out-of-bounds indexing caused by an attempt to unwordwrap an empty string.

The problem here is that the function `string_unwordwrap()` does not check that the string `result` isn't empty before attempting to index `result.size()-1`. If `result` is empty, then `result.size()` is 0, and `result.size()-1` becomes -1, and indexing a string at position -1 is always undefined behavior.

Funnily enough, a similar indexing happens just a few lines down, but this time, there is a check to make sure that the string isn't empty first. I'm unsure of how @Daaaav forgot that check a few lines earlier.

This situation can happen in practice, with custom level localizations. I made a level with a filename of `testloc.vvvvvv` and created a file at `lang/fr/levels/testloc/custom_cutscenes.xml` with the following content:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<cutscenes>
    <cutscene id="test" explanation="">
        <dialogue speaker="cyan" english="This is text..." translation="blarg"/>
    </cutscene>
</cutscenes>
```

Then I switched to French, created an internal script named `test`, and created a 0-line empty text box by creating a 12-line text box (because unless the number of lines is suffixed with `L`, the text box contents will be cleared when the 12th line is inserted). Running the script triggers the segfault. (Well, technically, on my machine, it triggers an assertion fail in libstdc++ and aborts, but that's basically the same thing.)

## Legal Stuff:

By submitting this pull request, I confirm that...

- [x] My changes may be used in a future commercial release of VVVVVV
- [x] I will be credited in a `CONTRIBUTORS` file and the "GitHub Friends"
  section of the credits for all of said releases, but will NOT be compensated
  for these changes

2024-01-19 15:40 UTC, Daaaav commented
> I'm unsure of how @Daaaav forgot that check a few lines earlier.

Oopsie, I guess that seemed like a place where we had to have added something to `result` already...

It's not correct that this will happen on an empty string though. That's what that _other_ `!result.empty()` is for. This specific segfault will only happen if the string starts with at least two newlines.

Other than that, the fix works (though I think it turns two newlines at the start of a string into one newline? So maybe we should make sure leading and trailing newlines work exactly as we want them to)

2024-01-20 23:11 UTC, InfoTeddy commented
> It's not correct that this will happen on an empty string though. That's what that _other_ `!result.empty()` is for. This specific segfault will only happen if the string starts with at least two newlines.
> 
> Other than that, the fix works (though I think it turns two newlines at the start of a string into one newline? So maybe we should make sure leading and trailing newlines work exactly as we want them to)

Thanks for the correction. I've updated the patch accordingly and the two leading newlines are now preserved accordingly.

2024-01-21 01:40 UTC, Daaaav requested changes

2024-01-21 01:40 UTC, Daaaav commented on desktop_version/src/Font.cpp
> +                }
```suggestion
                if (!result.empty())
                {
                    // The last character was already a newline, so change it back from the space we thought it should have become.
                    result[result.size()-1] = '\n';
                }
                else
                {
                    // The string starts with two or more newlines, in this case we didn't add the first one at all.
                    result.append("\n\n");
                }
```

2024-01-21 01:40 UTC, Daaaav commented on desktop_version/src/Font.cpp
>                  // The last character was already a newline, so change it back from the space we thought it should have become.
Just making sure the comment still makes sense... (In two parts because suggestions work that way apparently)

```suggestion
```

2024-01-21 01:49 UTC, InfoTeddy commented
Suggestions applied.

2024-01-21 01:51 UTC, Daaaav approved these changes

2024-01-21 01:52 UTC, merged