Checkpoint autosaving
TerryCavanagh/VVVVVV pull request #1174
Opened 2024-06-05 12:18 UTC by NyakoFox

## Changes:

This is a small PR that adds mobile VVVVVV's behavior of saving on checkpoints. It quicksaves whenever your checkpoint gets set, either by touching a checkpoint or `setcheckpoint()`. On by default on Android, off otherwise. Can be manually overridden through `settings.vvv`.

## Legal Stuff:

By submitting this pull request, I confirm that...

- [x] My changes may be used in a future commercial release of VVVVVV
- [x] I will be credited in a `CONTRIBUTORS` file and the "GitHub Friends"
  section of the credits for all of said releases, but will NOT be compensated
  for these changes unless there is a prior written agreement

2024-09-26 04:38 UTC, InfoTeddy reviewed
If the game fails to quicksave, there is no indication to the user (besides console output) that it has failed.

Also, this adds a new settings bool but there is no way to toggle it without manually editing the file. Should we add a menu option to toggle it?

Also (and this doesn't have to be done right now), I was wondering if we should add some sort of indication for a successful quicksave. Nothing as big as the teleporter "Game Saved" but something like a rotating icon in the corner that other games do would be good. (Of course it would be slightly misleading because we block the entire game thread for the write but it would still get the point across.)

2024-09-26 14:06 UTC, NyakoFox commented
> Also, this adds a new settings bool but there is no way to toggle it without manually editing the file. Should we add a menu option to toggle it?
Honestly, it feels like something that you should manually have to toggle if you know what you're doing -- we don't want people on Android to lose their progress. However, if people disagree, I can add a menu option.

2024-09-26 15:59 UTC, InfoTeddy commented
> Honestly, it feels like something that you should manually have to toggle if you know what you're doing -- we don't want people on Android to lose their progress. However, if people disagree, I can add a menu option. 

A menu option _would_ still be manually toggling it, and Android players would know fully well what the option does based off the name and description. If they decide to toggle it, that's on them.

2024-09-26 18:04 UTC, InfoTeddy requested changes
Attempts to quicksave are made in Time Trials, Intermission replays, No Death Mode, and custom levels, but they fail, so the error text box displays. (The Secret Lab doesn't have checkpoints so in practice it couldn't happen, but this issue also applies there.)

In particular we might want this feature to work for custom level quicksaves too. :stuck_out_tongue: Anyone know what the current mobile version behavior is for custom levels? I would hope it automatically writes custom level quicksaves too.

2024-09-26 18:04 UTC, InfoTeddy commented on desktop_version/src/Entity.cpp
> +                    if (game.gamesavefailed) {
```suggestion
                    if (game.gamesavefailed)
                    {
```

2024-09-26 18:04 UTC, InfoTeddy commented on desktop_version/src/Script.cpp
> +                    if (game.gamesavefailed) {
```suggestion
                    if (game.gamesavefailed)
                    {
```

2024-09-26 18:16 UTC, Daaaav commented
> 😛 Anyone know what the current mobile version behavior is for custom levels? I would hope it automatically writes custom level quicksaves too.

Yep, custom levels also autosave on mobile.

2024-09-28 00:14 UTC, InfoTeddy approved these changes

2024-09-28 00:14 UTC, merged