Set game as DPI-aware
TerryCavanagh/VVVVVV pull request #573
Opened 2021-01-01 01:50 UTC by leo60228

## Changes:

This prevents the OS from performing bilinear scaling in addition to whatever the game is doing. SDL_WINDOW_ALLOW_HIGHDPI should do this on all platforms, but it's only implemented for macOS, Wayland (X11 doesn't have a concept of DPI-awareness), and a few more esoteric ones. Windows has a few ways of doing it, but SetProcessDPIAware is the easiest. The docs say that this can cause unexpected behavior, but my understanding is that this relates to multithreading, and in this case nothing should be able to go wrong.

I don't currently have a way to do Windows builds locally, so I'm relying on CI to make sure this compiles. It'd be nice if someone could test it on HiDPI Windows/Wayland/macOS, but I'm pretty confident that this should work if it builds.
## Legal Stuff:

By submitting this pull request, I confirm that...

- [x] My changes may be used in a future commercial release of VVVVVV (for
  example, a 2.3 update on Steam for Windows/macOS/Linux)
- [x] I will be credited in a `CONTRIBUTORS` file and the "GitHub Friends"
  section of the credits for all of said releases, but will NOT be compensated
  for these changes

2021-01-01 02:10 UTC, InfoTeddy requested changes

2021-01-01 02:10 UTC, InfoTeddy commented on desktop_version/src/Screen.cpp
> +		SDL_GetRendererOutputSize(m_renderer, &winX, &winY);
This call should use `Screen::GetWindowSize()` like all other instances of this call.

2021-01-09 22:21 UTC, sylveon commented
The method used for Windows doesn't make the app per-monitor DPI aware, which means that if the game is played on a monitor other than the primary one, upscaling or downscaling of the application window may take place.

The documentation for the API also mentions that using the API instead of app manifests isn't recommended: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setprocessdpiaware

2021-01-09 22:24 UTC, InfoTeddy commented
Yep, the Microsoft docs you linked to were already discussed on the VVVVVV Discord server. Leo's reaction to the "unexpected application behavior" remark: "thanks for the detail there".

However, I did not know about the detail of per-monitor DPI awareness. Does using manifests fix this? The docs don't say.

2021-01-09 22:56 UTC, leo60228 commented
Well, VVVVVV *isn't* per-monitor DPI aware.

* No DPI awareness (default): From VVVVVV's perspective, it's always running on a standard DPI monitor, and Windows will upscale it to the correct DPI.
* System DPI awareness (this PR): From VVVVVV's perspective, it's always running on the same DPI monitor for the duration of the program, and Windows will upscale it to the current DPI if necessary. Since VVVVVV doesn't care what DPI the monitor is (it does its own upscaling no matter what), this is fine.
* Per-monitor DPI aware: VVVVVV sees the actual DPI of the monitor it's being displayed on at all times, and is expected to resize the window automatically upon a DPI change. This isn't implemented, and I'm not fully convinced that it should be.

There's also an additional issue with per-monitor DPI awareness: it wasn't introduced until Windows 8.1. While that's the oldest currently supported version of Windows, with how conservative the game is with minimum requirements in other regards, I assumed that keeping compatibility with Vista (or at least 7) was desired.

2021-01-09 23:02 UTC, sylveon commented
Yeah, [manifests allow to set per-monitor DPI awareness](https://docs.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process#setting-default-awareness-with-the-application-manifest).

Usually, programs would use a combination of both `dpiAware` and `dpiAwareness`, something like this:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
  <asmv3:application>
    <asmv3:windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/pm</dpiAware>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2</dpiAwareness>
    </asmv3:windowsSettings>
  </asmv3:application>
</assembly>
```

> There's also an additional issue with per-monitor DPI awareness: it wasn't introduced until Windows 8.1. While that's the oldest currently supported version of Windows, with how conservative the game is with minimum requirements in other regards, I assumed that keeping compatibility with Vista (or at least 7) was desired.

Manifests also makes handling the cases where per-monitor isn't available (on older OS for example) simpler, since the OS will automatically fallback to system-aware, instead of the program needing to try setting the DPI awareness until it succeeds.

To test the V1 per monitor DPI awareness on a machine with a recent OS version, one can simply remove the per monitor V2 entry as well.

> Per-monitor DPI aware: VVVVVV sees the actual DPI of the monitor it's being displayed on at all times, and is expected to resize the window automatically upon a DPI change. This isn't implemented, and I'm not fully convinced that it should be.

Unless `WM_DPICHANGED` has custom handling, Windows will automatically resize the window for you when changing DPIs. The game will see this size change as if the user grabbed the window and resized it manually. As you've said, the game does its own upscaling no matter what so this isn't an issue.

2021-01-09 23:04 UTC, leo60228 commented
The CMake version used by VVVVVV is too old to automatically handle app manifests, and I'm not sure of a good way to handle it without native CMake support.

2021-01-09 23:05 UTC, InfoTeddy commented
I talked with @flibitijibibo in Discord DMs about this earlier. He said that it's completely fine to just drag the manifest file alongside the executable, because it would at least be exposed to end users.

2021-01-10 01:21 UTC, flibitijibibo commented
Yeah, I'm okay with just having the manifest be manual - worst case we can just emit a warning at runtime if the file isn't found.

The alternative is to try and add programmatic support by dlopening user32.dll, but who knows how much further Windows hi-dpi is going to break... for FNA games we generally just ignore it and let people shove their own mainifest into the game folder. I don't think we can add it to SDL either, even though logically it should be there... Microsoft _really_ blew it with this API compared to macOS and Wayland.

2021-01-18 18:11 UTC, flibitijibibo commented
I've pulled in all the high-DPI changes in this patchset except for the Windows commit - the manifest is probably the way to go with this unless someone who _really_ likes Windows wants to write the dynamically loaded user32 stuff.

2021-01-18 18:11 UTC, closed without merging