Fix lab background's "backboxint" array only using the first generated value
TerryCavanagh/VVVVVV pull request #974
Opened 2023-05-12 11:51 UTC by kittrz9

## Changes:

This change makes boxes drawn in the background for The Lab have a slight variation in brightness to give a slight sense of depth similar to the starfield background. I assume that's what was intended, as the `backboxint` variable is used in that way but would only use the first value that is generated despite creating a value for each box. This change just makes it use the value corresponding to that box.

This change also sorts that array so that darker boxes will not appear over brighter ones. I'm not too sure if this is what would've been intended since it is unsorted in the original code, but this helps to give off that slight depth feeling (though I do feel like it's a very slight difference). The sorting shouldn't have too much of an affect on performance since it's only ran once during initialization and is only ran through for each box.

## Legal Stuff:

By submitting this pull request, I confirm that...

- [X] My changes may be used in a future commercial release of VVVVVV
- [X] I will be credited in a `CONTRIBUTORS` file and the "GitHub Friends"
  section of the credits for all of said releases, but will NOT be compensated
  for these changes

2023-05-12 12:32 UTC, kittrz9 commented
Sorry if I interpreted the code wrongly, I just stumbled across it and it seemed like a weird bug that was never caught.

Here's a comparison between the two, with the first image being with the fix (the change in background color is not part of this pull request and is just from the color being chosen randomly). The change is very subtle so I understand if you don't think it should be merged

![2023-05-12_06-20](https://github.com/TerryCavanagh/VVVVVV/assets/14117628/67a660b2-98be-446d-8ada-6f8f7b5b8bd4)
![2023-05-12_06-42](https://github.com/TerryCavanagh/VVVVVV/assets/14117628/2bb6dd5d-acae-4493-9159-e80a40d0d2da)

2023-05-12 17:04 UTC, InfoTeddy requested changes
Small nit. Still leaving it up to Terry if it should be merged.

2023-05-12 17:04 UTC, InfoTeddy commented on desktop_version/src/Graphics.cpp
> +#include <algorithm>
Includes need to be in alphabetical order.
```suggestion
#include <algorithm>
#include <SDL.h>
```

2023-05-13 15:59 UTC, TerryCavanagh commented
Hmm, yeah, I'm sorry, but I think it's less distracting when the background is all the one colour!

2023-05-17 15:48 UTC, closed without merging